site_name: SheronW's Notes
theme:
        name: material
markdown_extensions:
        - mdx_math
extra_javascript:
        - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
